name = "sg-rail-crowd"
type = "javascript"
main = "index.js"

account_id = "69ac6123a5f85c72102bb70ac9652da5"
workers_dev = true
zone_id = ""
compatibility_date = "2021-11-02"

kv_namespaces = [
   { binding = "CACHE", preview_id = "d21f3cc8750a4821a53bea52ed274308", id = "b70c3ffffca84d4780625e7f22e4cc77" }
]

[observability]
enabled = true

# [secrets]
# LTA_DATAMALL_ACCOUNT_KEY
